version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  flake8:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - run: pip install flake8
      - run: flake8
  pytest:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pip install pytest
      - run: echo app.config.update[SQLALCHEMY_DATABASE_URI='DB_URI']
      - run: pytest
  mypy:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pip install mypy
      - run: mypy methods.py
      - run: mypy database.py
workflows:
  first:
    jobs:
      - flake8
      - pytest
      - mypy

