version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  flake8:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - run: pip install flake8
      - run: flake8
  pytest:
    docker:
      - image: circleci/python:3.9.1
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pip install pytest
      - run: app.config['SQLALCHEMY_DATABASE_URI']='DB_URI'
      - run: pytest
workflows:
  first:
    jobs:
      - flake8
      - pytest

